volumes:
  snort_data:

services:
  me-sensor-snort:
    build: 
      context: snort/
    network_mode: host
    restart: always
    environment:
      - NETWORK_INTERFACE=enp2s0
    volumes:
      - ${PWD}/snort/snort.lua:/usr/local/etc/snort/snort.lua:ro
      - snort_data:/var/log/snort:rw

  me-sensor-snort-parser:
    image: mfscy/snort3-parser:latest
    depends_on:
      - me-sensor-snort
    restart: always
    environment:
      - MQTT_HOST=192.168.1.121
      - MQTT_PORT=1883
      # - MQTT_USERNAME=username
      # - MQTT_PASSWORD=password
      - SNORT_ALERT_FILE_PATH=/var/log/snort/alert_json.txt
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - snort_data:/var/log/snort:rw
