version: '3'

services:
  mqtt-source:
    image: mfscy/kafka-mqtt-source
    container_name: mqtt-source
    env_file:
      - conf/mqtt-source.env

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    env_file:
      - conf/zookeeper.env

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka
    ports:
      # - '9092:9092'
      - '9093:9093'
    env_file:
      - conf/kafka.env
    depends_on:
      - zookeeper

  control-center:
    image: provectuslabs/kafka-ui
    container_name: control-center
    depends_on:
      - zookeeper
      - kafka
      # - connect
      - mqtt-source
    ports:
      - "9021:8080"
    env_file:
      - conf/control-center.env
