version: '3'

services:
  connect-add:
    image: curlimages/curl
    container_name: connect-add
    depends_on:
      - zookeeper
      - kafka
      - connect
      - control-center
    volumes:
      - ./connector.json:/connector.json
    command: "curl -s -X POST -H 'Content-Type: application/json' --data @connector.json http://connect:8083/connectors"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka_mounts/logs
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  connect:
    image: 'bitnami/kafka:latest'
    container_name: connect
    hostname: connect
    ports:
      - '8083:8083'
    volumes:
      - './connect-distributed.properties:/opt/bitnami/kafka/config/connect-distributed.properties'
      - './kafka-connect-mqtt:/usr/share/java/kafka-connect-mqtt'
      - './kafka-connect-mqtt-kafka-3-1-assembly-4.0.0.jar:/usr/share/java/kafka-connect-mqtt/kafka-connect-mqtt-kafka-3-1-assembly-4.0.0.jar'
    depends_on:
      - zookeeper
      - kafka
    command: sh -c "sleep 10 && /opt/bitnami/kafka/bin/connect-distributed.sh /opt/bitnami/kafka/config/connect-distributed.properties"

  control-center:
    image: provectuslabs/kafka-ui
    container_name: control-center
    depends_on:
      - zookeeper
      - kafka
      - connect
    ports:
      - "9022:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: 'MataElangLab'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
      KAFKA_CLUSTERS_0_ZOOKEEPER: 'zookeeper:2181'
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: 'MataElangLabConnector'
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: 'http://connect:8083'

